### ISSUE TITLE
Incorrect keyword detection in VSCode

### ISSUE THREAD

**Issue by gamesbrainiac** [storyscript/sls#41]
Hi there!

There is an issue with the keyword detection in the VSCode plugin. Please take a look at the screenshot provided.
![Screenshot 2019-04-28 at 22 13 17](https://user-images.githubusercontent.com/3856600/56885127-f9698d80-6a6b-11e9-9107-cd6721b9e563.png)

You will see that on the first line, `list` is in a different colour then `en`. I think this is because it sees `list` as a keyword.

**Comment by wilzbach** [comment]
Hi, thanks a lot of reporting this.
I think the issue is due to the syntax file not being up-to-date (https://github.com/storyscript/syntax).
I will have a look into updating this tonight.

**Comment by gamesbrainiac** [comment]
@wilzbach Thanks Seb, also pleased to meet you :)

**Comment by wilzbach** [comment]
Upgraded the vscode to the newest grammar. It then shows this:

![image](https://user-images.githubusercontent.com/4370550/56929653-83e8d600-6ada-11e9-9744-aa0e800080c7.png)

The syntax file isn't perfect, but at least this basic error is gone ;-)
